# Security Configuration for AI Camera System

# Network Security
network_security:
  firewall_rules:
    - name: "Allow HTTP"
      port: 80
      protocol: tcp
      source: "0.0.0.0/0"
      action: allow
    - name: "Allow HTTPS"
      port: 443
      protocol: tcp
      source: "0.0.0.0/0"
      action: allow
    - name: "Allow SSH"
      port: 22
      protocol: tcp
      source: "YOUR_IP_RANGE/32"
      action: allow
    - name: "Block all other traffic"
      action: deny

  vpn_config:
    enabled: true
    type: "wireguard"
    allowed_ips: ["YOUR_VPN_RANGE/24"]

# Application Security
application_security:
  cors:
    allowed_origins:
      - "https://your-domain.com"
      - "https://www.your-domain.com"
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["Content-Type", "Authorization", "X-Requested-With"]
    allow_credentials: true
    max_age: 86400

  rate_limiting:
    window_ms: 900000  # 15 minutes
    max_requests: 100
    skip_successful_requests: false
    skip_failed_requests: false

  jwt_security:
    secret_key_length: 64
    algorithm: "HS256"
    expires_in: "24h"
    refresh_expires_in: "7d"
    issuer: "ai-camera-system"
    audience: "ai-camera-users"

  password_policy:
    min_length: 12
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_special_chars: true
    max_age_days: 90
    prevent_reuse: 5

# Database Security
database_security:
  ssl_mode: "require"
  connection_limit: 20
  idle_timeout: 300
  max_lifetime: 3600
  
  encryption:
    at_rest: true
    in_transit: true
    key_rotation_days: 90

  backup:
    encryption: true
    retention_days: 30
    location: "secure_backup_location"

# API Security
api_security:
  authentication:
    required: true
    methods: ["jwt", "api_key"]
    session_timeout: 3600

  authorization:
    role_based: true
    permissions:
      - resource: "cameras"
        actions: ["read", "write", "delete"]
        roles: ["admin", "operator"]
      - resource: "analytics"
        actions: ["read"]
        roles: ["admin", "analyst", "viewer"]
      - resource: "system"
        actions: ["read", "write"]
        roles: ["admin"]

  input_validation:
    enabled: true
    sanitize_inputs: true
    max_payload_size: "10mb"
    allowed_file_types: ["jpg", "jpeg", "png", "gif"]
    max_file_size: "5mb"

# Monitoring and Logging
security_monitoring:
  audit_logging:
    enabled: true
    level: "info"
    retention_days: 90
    sensitive_fields: ["password", "token", "secret"]

  intrusion_detection:
    enabled: true
    rules:
      - name: "Failed login attempts"
        threshold: 5
        window: 300
        action: "block_ip"
      - name: "SQL injection attempts"
        pattern: ".*(union|select|insert|delete|drop|create).*"
        action: "alert"
      - name: "XSS attempts"
        pattern: ".*<script.*"
        action: "alert"

  alerts:
    email_notifications: true
    slack_notifications: true
    sms_notifications: true
    escalation_policy:
      - level: 1
        timeout: 300
        contacts: ["admin@your-domain.com"]
      - level: 2
        timeout: 1800
        contacts: ["emergency@your-domain.com"]

# Infrastructure Security
infrastructure_security:
  container_security:
    run_as_non_root: true
    read_only_root: true
    no_new_privileges: true
    seccomp_profile: "default"
    apparmor_profile: "docker-default"

  secrets_management:
    provider: "hashicorp_vault"
    auto_rotation: true
    encryption_key_rotation: true

  network_policies:
    - name: "frontend-to-backend"
      from: ["frontend"]
      to: ["beauth", "becamera"]
      ports: [3001, 3002]
    - name: "backend-to-database"
      from: ["beauth", "becamera"]
      to: ["postgres", "redis"]
      ports: [5432, 6379]

# Compliance
compliance:
  gdpr:
    enabled: true
    data_retention_days: 90
    right_to_forget: true
    data_export: true

  hipaa:
    enabled: false  # Set to true if handling medical data
    phi_encryption: true
    audit_trails: true

  sox:
    enabled: true
    financial_data_protection: true
    access_controls: true

# Incident Response
incident_response:
  playbooks:
    - name: "Data Breach"
      steps:
        - "Isolate affected systems"
        - "Preserve evidence"
        - "Notify stakeholders"
        - "Assess impact"
        - "Implement remediation"
    - name: "Service Outage"
      steps:
        - "Assess scope"
        - "Implement workarounds"
        - "Restore services"
        - "Post-mortem analysis"

  contacts:
    security_team: "security@your-domain.com"
    legal_team: "legal@your-domain.com"
    pr_team: "pr@your-domain.com"
    emergency: "+1-555-EMERGENCY"

# Backup and Recovery
backup_recovery:
  automated_backups:
    frequency: "daily"
    retention: "30 days"
    encryption: true
    verification: true

  disaster_recovery:
    rto: "4 hours"
    rpo: "1 hour"
    backup_location: "geo_redundant"
    recovery_testing: "monthly"

# SSL/TLS Configuration
ssl_tls:
  minimum_version: "TLSv1.2"
  preferred_ciphers:
    - "ECDHE-RSA-AES256-GCM-SHA384"
    - "ECDHE-RSA-AES128-GCM-SHA256"
    - "DHE-RSA-AES256-GCM-SHA384"
  hsts:
    enabled: true
    max_age: 31536000
    include_subdomains: true
    preload: true 