services:
  becamera:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ai-camera-service
    ports:
      - "3002:3002"
    environment:
      - PYTHON_ENV=development
      - PORT=3002
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=people_counting_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - CORS_ORIGIN=http://localhost:3000
      - JWT_SECRET=your_super_secret_jwt_key_here_development
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    networks:
      - ai-camera-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ai-camera-network:
    driver: bridge 